name: astronum
grade: stable
adopt-info: astronum
license: GPL-3.0+

base: core22
confinement: strict

apps:
  astronum:
    command: usr/bin/com.github.alexkdeveloper.astronum
    extensions: [gnome-43]
    slots:
      - dbus-daemon
    common-id: com.github.alexkdeveloper.astronum

parts:
  astronum:
    plugin: meson
    source: https://github.com/alexkdeveloper/astronum.git
    source-branch: main
    meson-parameters: [--prefix=/snap/astronum/current/usr]
    build-packages:
      - gettext
    organize:
      snap/astronum/current/usr: usr
    parse-info: [usr/share/appdata/com.github.alexkdeveloper.astronum.appdata.xml]

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.alexkdeveloper.astronum
